-- Reconstructed from entity classes + MyBatis mapper XML (original schema.sql never existed in the repo).
-- Recreates the same 10 tables the mappers in server/src/main/resources/mapper/*.xml query.

CREATE TABLE IF NOT EXISTS USER_MASTER (
    USER_ID       VARCHAR(50)  NOT NULL,
    USER_NAME     VARCHAR(50)  NOT NULL,
    USER_PSWD     VARCHAR(255) NOT NULL,
    USER_MAIL     VARCHAR(255) NOT NULL,
    USER_IMG_PATH VARCHAR(255),
    JOIN_DATE     DATETIME     NOT NULL,
    USER_ROLE     CHAR(1)      NOT NULL DEFAULT 'U',
    USER_STATUS   CHAR(1)      NOT NULL DEFAULT 'N',
    POINT_BALANCE INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UK_USER_MAIL (USER_MAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECIPE_MASTER (
    RECIPE_ID      VARCHAR(50)  NOT NULL,
    USER_ID        VARCHAR(50)  NOT NULL,
    CATEGORY_ID    VARCHAR(50),
    TITLE          VARCHAR(200) NOT NULL,
    RCP_DISC       TEXT,
    COOK_TIME      VARCHAR(50),
    COOK_DFCT      VARCHAR(50),
    RGT_DATE       DATETIME     NOT NULL,
    UPD_DATE       DATETIME,
    IMG_URL        VARCHAR(255),
    RECIPE_INGR    TEXT,
    RECIPE_TIP     TEXT,
    RECIPE_TAG     VARCHAR(255),
    VIEW_COUNT     INT          NOT NULL DEFAULT 0,
    CLAIMED_POINT  INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (RECIPE_ID),
    KEY IDX_RECIPE_USER (USER_ID),
    CONSTRAINT FK_RECIPE_USER FOREIGN KEY (USER_ID) REFERENCES USER_MASTER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECIPE_STEP (
    RECIPE_ID        VARCHAR(50) NOT NULL,
    STEP_ORDER       INT         NOT NULL,
    STEP_DESCRIPTION TEXT,
    PRIMARY KEY (RECIPE_ID, STEP_ORDER),
    CONSTRAINT FK_STEP_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE_MASTER (RECIPE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECIPE_VIEW_LOG (
    ID         BIGINT AUTO_INCREMENT,
    RECIPE_ID  VARCHAR(50) NOT NULL,
    USER_ID    VARCHAR(50) NOT NULL,
    VIEWED_AT  DATETIME    NOT NULL,
    VIEW_DAY   DATE        NOT NULL,
    PRIMARY KEY (ID),
    KEY IDX_VIEW_LOOKUP (RECIPE_ID, USER_ID, VIEW_DAY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CODE_MANAGE (
    CODE_HEAD   VARCHAR(50)  NOT NULL,
    CODE        VARCHAR(50)  NOT NULL,
    CODE_NAME   VARCHAR(100) NOT NULL,
    PARENT_CODE VARCHAR(50),
    USE_YN      CHAR(1)      NOT NULL DEFAULT 'Y',
    CODE_SORT   INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (CODE_HEAD, CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CTG = 레시피 카테고리, LV = 난이도 (LV의 CODE는 표시 라벨과 동일하게 맞춰서
-- RECIPE_MASTER.COOK_DFCT에 저장된 값과 코드 조회 없이 바로 일치하도록 함).
INSERT IGNORE INTO CODE_MANAGE (CODE_HEAD, CODE, CODE_NAME, PARENT_CODE, USE_YN, CODE_SORT) VALUES
('CTG', 'CTG01', '한식', NULL, 'Y', 1),
('CTG', 'CTG02', '양식', NULL, 'Y', 2),
('CTG', 'CTG03', '중식', NULL, 'Y', 3),
('CTG', 'CTG04', '일식', NULL, 'Y', 4),
('CTG', 'CTG05', '분식', NULL, 'Y', 5),
('CTG', 'CTG06', '디저트/베이킹', NULL, 'Y', 6),
('CTG', 'CTG07', '안주', NULL, 'Y', 7),
('CTG', 'CTG08', '다이어트/샐러드', NULL, 'Y', 8),
('LV', '쉬움', '쉬움', NULL, 'Y', 1),
('LV', '중간', '중간', NULL, 'Y', 2),
('LV', '어려움', '어려움', NULL, 'Y', 3);

-- Schema for this table was already documented in EmailVerificationMapper.xml; used as-is.
CREATE TABLE IF NOT EXISTS EMAIL_VERIFICATION (
    USER_ID     VARCHAR(50)  NOT NULL,
    USER_MAIL   VARCHAR(255) NOT NULL,
    CODE        VARCHAR(10)  NOT NULL,
    EXPIRES_AT  DATETIME     NOT NULL,
    VERIFIED_YN CHAR(1)      DEFAULT 'N',
    CREATED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_CODE (
    ID         BIGINT AUTO_INCREMENT,
    USER_ID    VARCHAR(50)  NOT NULL,
    USER_MAIL  VARCHAR(255) NOT NULL,
    CODE       VARCHAR(10)  NOT NULL,
    EXPIRES_AT DATETIME     NOT NULL,
    USED_YN    CHAR(1)      NOT NULL DEFAULT 'N',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID    VARCHAR(50)  NOT NULL,
    PRODUCT_NAME  VARCHAR(200) NOT NULL,
    PRODUCT_POINT INT          NOT NULL DEFAULT 0,
    MAIN_IMAGE    VARCHAR(255),
    CREATED_AT    DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS POINT_LEDGER (
    LEDGER_ID        BIGINT AUTO_INCREMENT,
    USER_ID          VARCHAR(50) NOT NULL,
    POINT_CHANGE     INT         NOT NULL,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION      VARCHAR(255),
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LEDGER_ID),
    KEY IDX_LEDGER_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PURCHASE_HISTORY (
    ID             BIGINT AUTO_INCREMENT,
    USER_ID        VARCHAR(50) NOT NULL,
    PRODUCT_ID     VARCHAR(50) NOT NULL,
    QTY            INT         NOT NULL DEFAULT 1,
    PURCHASE_DATE  DATETIME    NOT NULL,
    PRIMARY KEY (ID),
    KEY IDX_PURCHASE_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECIPE_COMMENT (
    COMMENT_ID  BIGINT AUTO_INCREMENT,
    RECIPE_ID   VARCHAR(50)   NOT NULL,
    USER_ID     VARCHAR(50)   NOT NULL,
    CONTENT     VARCHAR(1000) NOT NULL,
    CREATED_AT  DATETIME      DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COMMENT_ID),
    KEY IDX_COMMENT_RECIPE (RECIPE_ID),
    CONSTRAINT FK_COMMENT_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE_MASTER (RECIPE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECIPE_LIKE (
    LIKE_ID     BIGINT AUTO_INCREMENT,
    RECIPE_ID   VARCHAR(50) NOT NULL,
    USER_ID     VARCHAR(50) NOT NULL,
    CREATED_AT  DATETIME    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LIKE_ID),
    UNIQUE KEY UK_LIKE_RECIPE_USER (RECIPE_ID, USER_ID),
    KEY IDX_LIKE_RECIPE (RECIPE_ID),
    CONSTRAINT FK_LIKE_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE_MASTER (RECIPE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHOP_REVIEW (
    REVIEW_ID   BIGINT AUTO_INCREMENT,
    PRODUCT_ID  VARCHAR(50)  NOT NULL,
    USER_ID     VARCHAR(50)  NOT NULL,
    RATING      TINYINT      NOT NULL,
    CONTENT     VARCHAR(1000) NOT NULL,
    CREATED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REVIEW_ID),
    KEY IDX_REVIEW_PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_REVIEW_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHOP_INQUIRY (
    INQUIRY_ID  BIGINT AUTO_INCREMENT,
    PRODUCT_ID  VARCHAR(50)  NOT NULL,
    USER_ID     VARCHAR(50)  NOT NULL,
    CONTENT     VARCHAR(1000) NOT NULL,
    CREATED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (INQUIRY_ID),
    KEY IDX_INQUIRY_PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_INQUIRY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
